DELETE http://localhost:3001/api/persons/137 HTTP/1.1

###

GET http://localhost:3001/api/persons HTTP/1.1

###

GET http://localhost:3001/info HTTP/1.1

###

GET http://localhost:3001/api/persons/69ea78806903cac5c67c74d0 HTTP/1.1

###

POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Donny MacDonald",
    "number": "800 234 7845"
}

###

PUT http://localhost:3001/api/persons/69ea78806903cac5c67c74d0 HTTP/1.1
Content-Type: application/json

{
    "name": "Tim Thornback",
    "number": "360 502 0027"
}